steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/h2ox-data-${_H2OX_EXT}', '--build-arg', 'MAIN=${_MAIN}','.']
images:
- 'gcr.io/$PROJECT_ID/h2ox-data-${_H2OX_EXT}'